import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Reject Modernity, Embrace Masculinity</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Reject Modernity, Embrace Masculinity</h1>
        <div
          style={{
            position: "relative",
            width: "200px",
            paddingBottom: "100px",
            left: "50%",
            transform: "translateX(-50%)",
          }}
        >
          <Image
            src="/images/zyzz-pose.jpg"
            alt="zyzz"
            layout="fill"
            objectFit="contain"
            priority
          />
        </div>
        <div>Get up you lazy</div>
        <p>Yeah buddy, light weight baby</p>
      </main>
    </>
  );
}
